### ISSUE TITLE
Uncaught Error: Cannot find module './build/quokka'

### ISSUE THREAD

**Issue by gra-ch** [wallabyjs/atom-quokka#10]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Unknown Windows version
**Thrown From**: [atom-quokka](https://github.com/wallabyjs/atom-quokka) package 1.0.92

### Stack Trace

Uncaught Error: Cannot find module './build/quokka'

```
At module.js:545

Error: Cannot find module './build/quokka'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.30.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.30.0/resources/app/src/module-cache.js:354:58)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/atom-quokka/node_modules/quokka-atom/index.js:1:224)
    at /packages/atom-quokka/node_modules/quokka-atom/index.js:2:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.30.0/resources/app/src/compile-cache.js:240:29)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (~/AppData/Local/atom/app-1.30.0/resources/app/src/native-compile-cache.js:66:33)
    at Immediate._onImmediate (/packages/atom-quokka/lib/quokka.js:9:22)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

### Commands

```
```

### Non-Core Packages

```
atom-live-server 2.3.0 
atom-quokka 1.0.92 
teletype 0.13.3 
```

**Comment by smcenlly** [comment]
Could you please try uninstalling and reinstalling your Quokka plugin?
