### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by donniereese** [wallabyjs/atom-quokka#2]
[Enter steps to reproduce:]

1. Install atom-quokka
2. when using nvm, set path to node version in config file.
3. Restart Atom

**Atom**: 1.19.5 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.6
**Thrown From**: [atom-quokka](https://github.com/wallabyjs/atom-quokka) package 1.0.8

### Stack Trace

Uncaught Error: spawn EACCES

```
At internal/child_process.js:313

Error: spawn EACCES
    at exports._errnoException (util.js:1022:11)
    at ChildProcess.spawn (internal/child_process.js:313:11)
    at Object.exports.spawn (child_process.js:399:9)
    at /packages/atom-quokka/node_modules/quokka-atom/build/extension/dist/wallaby/client.js:14:1083
    at /packages/atom-quokka/node_modules/quokka-atom/build/extension/dist/wallaby/client.js:14:3085)
    at Object.onceWrapper (events.js:290:19)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitCloseNT (net.js:1544:8)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

### Commands

```
     -9:58.4.0 quokka:create-javascript-file (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 1.2.0 
acute-syntax 1.0.0 
aesthetic-ui 2.0.0 
atom-beautify 0.29.17 
atom-easy-jsdoc 4.12.1 
atom-material-syntax 1.0.2 
atom-material-ui 1.3.9 
atom-quokka 1.0.8 
base16-ocean-dark-syntax-theme 0.1.10 
batman-syntax 1.1.0 
black-ui 0.3.4 
chester-atom-syntax 0.2.0 
docblockr 0.11.0 
dracula-ui 0.6.0 
duotone-blue-dark-syntax 1.4.0 
duotone-bright-sea-syntax 2.1.0-4 
duotone-dark-amethyst-syntax 2.0.4 
duotone-dark-forest-syntax 2.1.0 
duotone-dark-sea-syntax 2.1.0 
duotone-dark-space-muted-syntax 1.0.0 
duotone-dark-space-syntax 2.1.0 
duotone-darkpool-syntax 1.1.0 
duotone-denim-syntax 0.4.1 
duotone-dusk-syntax 0.3.0 
emmet 2.4.3 
firewatch-syntax 1.1.1 
genesis-syntax 1.0.9 
genesis-ui 0.5.0 
gl-dark-syntax 3.0.0 
gl-light-syntax 3.0.0 
hydra-syntax-theme 3.0.1 
imdone-atom 2.2.6 
isotope-ui 2.8.5 
json-colorer 1.0.0 
katana-syntax 0.1.0 
ker0x-syntax 0.1.3 
keyboard-sounds 0.2.0 
lample-syntax 0.1.1 
language-markdown 0.19.1 
language-pug 0.0.21 
linter 1.11.23 
linter-eslint 8.1.2 
linter-htmlhint 1.3.2 
linter-scss-lint 3.1.0 
malachite-syntax 0.1.0 
mechanical-keyboard-1 0.1.4 
min-ui 0.0.4 
minimal-syntax 0.21.0 
minimal-syntax-dark 0.6.0 
minimap 4.29.3 
native-ui 0.20.6 
nord-atom-syntax 0.9.1 
northem-atom-syntax 2.0.0 
northem-atom-ui 2.0.0 
northem-dark-atom-syntax 2.0.0 
northem-dark-atom-ui 2.0.0 
nucleus-dark-ui 0.11.0 
pigments 0.39.1 
platformio-ide-terminal 2.5.3 
seti-syntax 1.1.2 
seti-ui 1.6.1 
slack-ui 0.8.0 
slack-ui-alter 0.8.3 
smart-backspace 0.2.3 
spacegray-dark-neue-syntax 1.4.2 
spacegray-dark-neue-ui 1.7.1 
spacegray-light-neue-ui 0.1.7 
spacegray-light-ui 0.1.0 
string-theory 0.1.1 
todo-show 1.11.0 
tron-theme 0.3.2 
vivid-syntax 2.1.0 
```

**Comment by ArtemGovorov** [comment]
Try opening your Atom Dev Tools (`Cmd + Alt + I`) console and executing:
```javascript
require('child_process').spawn("...")
``` 
where `...` is the node path that you are setting in quokka config, and let me know what happens.
